run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - unused
    - varcheck
