run:
  timeout: 5m

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  lll:
    line-length: 200
  misspell:
    locale: US
  staticcheck:
    go: "1.23"

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - whitespace

issues:
  exclude-dirs:
    - pkg/plugin/aes
  exclude:
    - "KMSv1 is deprecated in v1.28 and will only receive security updates going forward. Use KMSv2 instead."
