FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.21-openshift-4.16 as builder

WORKDIR /go/src/github.com/Azure/kubernetes-kms

COPY . .

RUN go build -o _output/kubernetes-kms ./cmd/server/

FROM registry.access.redhat.com/ubi9:latest
COPY --from=builder /go/src/github.com/Azure/kubernetes-kms/_output/kubernetes-kms /usr/bin/kubernetes-kms

ENTRYPOINT [ "/usr/bin/kubernetes-kms" ]

LABEL io.openshift.release.operator=true