FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.18 AS builder

WORKDIR /go/src/github.com/Azure/kubernetes-kms

COPY . .

RUN go build -o _output/kubernetes-kms ./cmd/server/

FROM registry.ci.openshift.org/ocp/4.18:base-rhel9
COPY --from=builder /go/src/github.com/Azure/kubernetes-kms/_output/kubernetes-kms /usr/bin/kubernetes-kms

ENTRYPOINT [ "/usr/bin/kubernetes-kms" ]

LABEL io.openshift.release.operator=true