jobs:
  - job: soak_test_aks_engine
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 5

    workspace:
      clean: all

    variables:
      - group: kubernetes-kms-soak-aks-engine

    steps:
      - script: make e2e-install-prerequisites
        displayName: "Install e2e test prerequisites"

      - script: |
          key=$(cat <<-END
          -----BEGIN RSA PRIVATE KEY-----
          $(CLIENT_KEY)
          -----END RSA PRIVATE KEY-----
          END
          )

          kubectl config set-cluster kms-aks-engine --server=$(API_SERVER_ENDPOINT)
          kubectl config set clusters.kms-aks-engine.certificate-authority-data $(CA_DATA)
          kubectl config set-credentials cluster-admin
          kubectl config set users.cluster-admin.client-certificate-data $(CLIENT_CERTIFICATE_DATA)
          kubectl config set users.cluster-admin.client-key-data "$(echo "$key" | base64 -i -)"
          kubectl config set-context kms --user=cluster-admin --cluster=kms-aks-engine
          kubectl config use-context kms
        displayName: "Set KUBECONFIG"

      - template: cluster-health-template.yml

      - script: make e2e-test
        displayName: "Run e2e tests"