jobs:
  - job: unit_tests
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    variables:
      - group: kubernetes-kms

    steps:
      - task: GoTool@0
        inputs:
          version: 1.17
      - script: make lint
        displayName: Run lint
      - script: make unit-test
        displayName: Run unit tests
      - script: make build
        displayName: Build
      - script: |
          sudo ./_output/kubernetes-kms --version
        displayName: Check binary version
      - script: |
          sudo mkdir /etc/kubernetes
          echo -e '{\n    "tenantId": "'$TENANT_ID'",\n    "subscriptionId": "'$SUBSCRIPTION_ID'",\n    "aadClientId": "'$CLIENT_ID'",\n    "aadClientSecret": "'$CLIENT_SECRET'",\n}' | sudo tee --append /etc/kubernetes/azure.json  > /dev/null
          sudo chown root:root /etc/kubernetes/azure.json && sudo chmod 600 /etc/kubernetes/azure.json
        displayName: Setup azure.json on host
        env:
          CLIENT_ID: $(AZURE_CLIENT_ID)
          CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      - script: |
          sudo ./_output/kubernetes-kms --keyvault-name $KV_NAME --key-name $KV_KEY --key-version $KV_KEY_VERSION --listen-addr "unix:///opt/azurekms.sock" > /dev/null &
          echo Waiting 2 seconds for the server to start
          sleep 2
          make integration-test
        displayName: Run integration tests
      - template: scan-images-template.yml
