jobs:
  - job: e2e_tests
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    variables:
      - group: kubernetes-kms

    steps:
      - task: GoTool@0
        inputs:
          version: 1.15

      - script: make e2e-install-prerequisites
        displayName: "Install e2e test prerequisites"
      - script: make e2e-setup-kind
        displayName: "Setup kind cluster with azure kms plugin"
        env:
          CLIENT_ID: $(AZURE_CLIENT_ID)
          CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      - script: |
          kubectl wait --for=condition=ready node --all
          kubectl wait pod -n kube-system --for=condition=Ready --all
          kubectl get nodes -owide
          kubectl cluster-info
        displayName: "Check cluster's health"
      - script: |
          docker exec kms-control-plane bash -c "cat /etc/kubernetes/manifests/kubernetes-kms.yaml"
          docker exec kms-control-plane bash -c "cat /etc/kubernetes/manifests/kube-apiserver.yaml"
          docker exec kms-control-plane bash -c "cat /etc/kubernetes/encryption-config.yaml"
          docker exec kms-control-plane bash -c "journalctl -u kubelet > kubelet.log && cat kubelet.log"

          docker exec kms-control-plane bash -c "cd /var/log/containers ; cat *"
          docker network ls
        displayName: "Debug logs"
        condition: failed()
      - script: make e2e-test
        displayName: "Run e2e tests"
      - script: |
          kubectl logs -l component=azure-kms-provider -n kube-system --tail -1
          kubectl get pods -o wide -A
        displayName: "Get logs"
      - script: make e2e-delete-kind
        displayName: "Delete cluster"
