trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool: staging-pool

jobs:
  - template: templates/unit-tests-template.yml
  - template: templates/soak-test-template.yml
  - template: templates/e2e-upgrade-template.yml
