trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool:
  vmImage: ubuntu-latest

jobs:
  - template: unit-tests-template.yml
  - template: e2e-kind-template.yml
