trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*
      - README.md
      - .github/*

pool: staging-pool

jobs:
  - template: templates/unit-tests-template.yml
  - template: templates/e2e-kind-template.yml
