trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*

pool:
  vmImage: ubuntu-latest

jobs:
  - template: unit-tests-template.yml
  # - template: e2e-kind-template.yml
  - template: templates/e2e-upgrade-template.yml
