jobs:
  - job: unit_tests
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    variables:
      - group: kubernetes-kms

    steps:
      - task: GoTool@0
        inputs:
          version: 1.15
      - script: V=1 make build
        displayName: Build
      - script: make unit-test
        displayName: Run unit tests
      - script: |
          sudo mkdir /etc/kubernetes
          echo -e '{\n    "tenantId": "'$TENANT_ID'",\n    "subscriptionId": "'$SUBSCRIPTION_ID'",\n    "aadClientId": "'$CLIENT_ID'",\n    "aadClientSecret": "'$CLIENT_SECRET'",\n    "resourceGroup": "'$KV_RESOURCE_GROUP'",\n    "location": "'$AZURE_LOCATION'",\n    "providerVaultName": "'$KV_NAME'",\n    "providerKeyName": "'$KV_KEY'",\n    "providerKeyVersion": "'$KV_KEY_VERSION'"\n}' | sudo tee --append /etc/kubernetes/azure.json  > /dev/null
        displayName: Setup azure.json on host
        env:
          CLIENT_ID: $(AZURE_CLIENT_ID)
          CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
      - script: |
          sudo ./_output/kubernetes-kms > /dev/null &
          echo Waiting 2 seconds for the server to start
          sleep 2
          make integration-test
        displayName: Run integration tests
      - template: scan-images.yml
